= Un jeu de carte Chinois très populaire

_NOM1, Prénom1, no_étudiant1, NC1_, _git login_

_NOM2, Prénom2, no_étudiant2, NC2_, _git login_

_GIT url_ 

L'objet de ce mini-projet est de développer le jeu de carte https://boardgamegeek.com/boardgame/70451/zheng-fen[zheng-fen] qui doit fonctionner en mode commande en ligne. Le jeux doit permettre de jouer contre un à trois autres adversaires qui sont des Joueurs Virtuels **JV**. Chaque JV est joue grace à un Moteur d'Inference **MI** executé par une class de votre programme. Un MI peut jouer comme un enfant (applique une stratégie basique) ou bien jouer certaines stratégies. Le déroulé d'une partie est contenu dans un terminal (pas d'interface graphique).

Vous devrez respecter les contraintes fonctionnelles et techniques mentionnées ci-dessous.

[IMPORTANT]
====
Vous respecterez les contraintes de développements suivantes:

* Ce mini-projet est à réaliser en Java par groupe de 2 étudiants.
  - les 2 étudiants doivent coopérer à travers un même git. Un des deux étudiants devra permettre à l'autre d'utiliser son git. Chaque utilisateur devra faire au moins un "merge request". 
* Il devra comporter une documentation dans ce git.
  - La documentation devra décrire l'usage de l'application (_manuel utilisateur_) ainsi que la conception du jeu (_manuel technique_).
  - La documentation doit être un fichier `.md` ou `.adoc` et accessible depuis le `git`
* Vous utiliserez `git` en effectuant des commits réguliers comportant des messages informatifs. L'usage des "pull requests" est également exigé, montrant ainsi votre collaboration au sein du groupe. 
* Le _build_ sera assuré par _Maven_ et plus précisément _Maven wrapper_ (déjà intégré dans le projet).
Aucune manipulation en dehors de Maven ne devra être nécessaire.
* La version de Java à utiliser est la https://adoptium.net/[version 17].
* Le _build_ devra intégrer `checkstyle` pour la vérification des règles de codages Google.
Le projet devra donc les respecter.
`checkstyle` devra être exécuté automatiquement durant la phase `validate` du cycle de vie par défaut.

* Des tests unitaires https://junit.org/junit5/docs/current/user-guide/[JUnit 5] (version https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter/5.9.1[_5.9.1_]) devront être disponibles pour la plupart des méthodes développées.

* Un outil de https://fr.wikipedia.org/wiki/Couverture_de_code[_Code Coverage_] devra être intégré au _build_

* Les fonctionnalités du langage Java devront être utilisées au mieux (POO, exceptions, librairie de collections, I/O, …).
* L'application devra pouvoir être exécutée à partir d'un `jar` incluant toutes les dépendances.
====

== Description de l'application à réaliser

* Pour chaque tour du jeu, l'interface:

  - visualisera les actions de chaque joueur par des messages textuels clairs. Par exemple, une action peut être _"je mets 3 rois suivie de 2 cartes de valeur 8"_.
    
  - doit afficher chaque joueur et ses messages dans une couleur distincte.

  - doit vérifier si la phrase est correcte et si sa proposition est valide en répondant de __manière très polie__. Exemple: "désolé XXX, mais vous n'avez qu'un roi"


  - doit afficher le nombre de cartes de chaque joueur, mais pas les valeurs qui possèdent.

  - doit afficher vos cartes, de manière ordonnées du plus fort au plus faible suivant l'ordre décrit ci-dessous.

  - doit pour toutes les actions effectuées par l'application afficher un message clair. Par exemple, si il y a mélange les cartes, un messages du type, "je viens de ...." sera affiché

*  l'application coordonne le jeu de 2 à 4 joueurs.

*  l'application doit s'assurer qu'une partie se termine bien et permettre au joueur qui a gagné de débuter la nouvelle partie.


== Contraintes à respecter

* C'est toujours à un des JV de distribuer les cartes. C'est le dernier joueur qui a gagné qui commence. Au début, on peut choisir celui qui a l'as de pic pour débuter.

* Dans ce jeu, un joueur peu décider d'abandonner si il juge qu'il n'a aucune chance de gagner. C'est un événement rare (surtout chez les JV), mais possible.

* L'ordre du plus fort au plus faible des cartes doit être: Le joker est le plus grand, suivie du 2, 1 (as), roi, ... 3.

* On mémorisera l'historique d'une partie dans une collection qui sera stocké dans un fichier.
    - il sera par exemple possible de rejouer une partie.

* Une interface spécifique pourra être proposée pour une aide ou pour voir le nombre de parties gagnées par chaque joueur.


* Vous devez implementer un Moteur d'Inférence **MI** qui joue comme un enfant.

  ** L'enfant se débarrasse de ses cartes au fur et à mesure de ce qu'il peut.

* Vous devez également implémenter un MI qui joue de manière plus "intelligente". 

  ** Par exemple, je peux jouer 1, 2 ou 3 cartes identiques, mais si j'ai 3 cartes identiques, je peux aussi decider de jouer une par une, ou bien de jouer une suivie de deux. 

  ** Il existe de nombreux autres stratégies. Ces stratégies dépendent des cartes en main. La problématique est de décider comment "assembler vos cartes" pour optimiser vos chances de pouvoir les débarrasser le plus rapidement possible.

  ** Notez que plus les cartes sont faibles, plus elles sont difficiles à s'en débarrasser.

  ** Au delà de deux MI et si ils sont _vraiment différents_ et que vous expliquez dans le rapport, vous aurez des points bonus

* Une interface spécifique pourra être proposée pour "espionner" un joueur. En d'autres termes, il est possible d'afficher les sorties d'un `MI` et voir ses cartes pour comprendre sa décision. Cela peut être le log d'un MI qui affiche chacune de ses décisions.

* Si vous avez `m` MI et `v` JV, le JV[i] i in (0..v-1) est piloté par le MI[i modulo m]. Chaque joueur virtuel est donc associé à un `MI` différent.



== Références

**Attention**: il existe plusieurs variantes, mais celui de reference est dans le premier lien avec les contraintes ci-dessus.

* Description du jeu:
  - https://boardgamegeek.com/boardgame/70451/zheng-fen
  - https://chrisenvadrouille.wordpress.com/2013/07/05/jour-46-les-regles-dun-jeu-de-cartes-chinois/
  - https://www.pagat.com/climbing/doudizhu.html


* Quelques bibliothèques :
http://fusesource.github.io/jansi/[JAnsi] (couleur dans un terminal),
https://github.com/jline/jline3[JLine] (gestion des saisies)

== Manuel utilisateur

> À compléter de manière exhaustive:
> Comment est gérer les différents utilisateurs ?
> Décrire la technique utiliser pour décider comment les joueurs virtuels décide l'assemblage des cartes. ?
> Y a t il possibilité qu'un joueur change d'assemblage des cartes en cours de parties et dans tout les cas décrire le pourquoi et le comment ? 
> Quelles sont les modifications/extensions à apporter si l'on veut qu'il n'y ai que des joueurs virtuels ?
> Quelles améliorations peut on envisager pour rendre le jeu plus intéressant/performant pour l'utilisateur ?
> Quelles évolutions peut-on envisager ?

== Manuel technique
=== Compiler le projet
.Sous Linux
----
$ ./mvnw package
----

.Sous Windows
----
> mvnw.cmd package
----

=== Exécuter l'application
----
$ java -jar target/zhangyao-1.0.jar
----

> À compléter :
> Comment consulter le rapport de couverture de code par les tests ?
> Quelles bibliothèques ont été utilisées et pourquoi ?
> Quel est le rôle des différentes classes ?
> Quels traitements sont réalisés pour gérer une commande saisie par l'utilisateur ? Donnez un exemple.
> Quelles améliorations peut-on envisager ?
