= Un jeu de carte chinois très populaire

== Identité
Complétez les informations ci-dessous.

_NOM1, Prénom1, no_étudiant1, NC1_, _git login_

_NOM2, Prénom2, no_étudiant2, NC2_, _git login_

_GIT url_ 

== Sujet
L'objet de ce mini-projet est de développer le jeu de carte Zheng Shangyou (争上游)  qui doit fonctionner en mode ligne de commande.
La règle du jeu est disponible ici http://persee.prism.uvsq.fr/pub/cp/prj/ZhengShangyou.html[ZhengShangyou].

Vous devrez respecter les contraintes techniques et fonctionnelles mentionnées ci-dessous.
L'usage de bibliothèques tierces est autorisé.
Ce qui n'est pas imposé par le sujet est laissé à votre libre interprétation.

=== Contraintes techniques
* Ce mini-projet est à réaliser en Java par groupe de 2 étudiants.
  - les 2 étudiants doivent coopérer à travers un même git (celui créé par _github classroom_).
  Les contributions des participants (_commits_) doivent être équilibrées.
* Il devra comporter une documentation dans ce fichier (cf. ci-dessous).
  - La documentation devra décrire l'usage de l'application (_manuel utilisateur_) ainsi que la conception du jeu (_manuel technique_).
* Vous utiliserez `git` en effectuant des commits réguliers comportant des messages informatifs.
L'usage des branches est également exigé, attestant ainsi de votre collaboration au sein du groupe.
* La version de Java à utiliser est la https://adoptium.net/[version 17] (ou plus récente).
* Le _build_ sera assuré par _Maven_ et plus précisément _Maven wrapper_ (déjà intégré dans le projet).
Aucune manipulation en dehors de Maven ne devra être nécessaire pour la compilation.
* Le projet devra respecter les règles de codage Google (vérification par `checkstyle` déjà intégré dans le projet).
* Des tests unitaires https://junit.org/junit5/docs/current/user-guide/[JUnit 5] devront être disponibles pour une part significative des méthodes développées.
* Un outil de https://fr.wikipedia.org/wiki/Couverture_de_code[_Code Coverage_] devra être intégré au _build_
* Les fonctionnalités du langage Java devront être utilisées au mieux (POO, exceptions, librairie de collections, I/O, …).
* L'application devra pouvoir être exécutée à partir d'un `jar` incluant toutes les dépendances.
* L'application fonctionnera dans un terminal (pas d'interface graphique).

=== Description fonctionnelle
L'application doit permettre de jouer de 2 à 4 joueurs, i.e. contre un à trois adversaires virtuels dénommés _Joueurs Virtuels_ (**JV**).
Chaque JV joue grace à un _Moteur de Jeu_ (**MJ**) modélisé par une classe de votre programme.
Un MJ peut jouer comme un enfant qui applique une stratégie basique, ou bien jouer à l'aide de stratégies plus sophistiquées.
Bien entendu, l'application doit gérer l'enchaînement des manches{empty}footnote:[Une manche se termine quand il ne reste des cartes qu'à un seul joueur (cf. la règle du jeu).] et les décomptes des points jusqu'à la fin du jeu{empty}footnote:[Le jeu se termine lorsqu'un joueur atteint ou dépasse un certain nombre de points (500 en général).].

==== Interface de l'application
* visualisera les actions de chaque joueur par des messages textuels clairs.
* Par exemple, une action peut être _"je mets 3 rois suivis de 2 cartes de valeur 8"_.  
* doit afficher chaque joueur et ses messages dans une couleur distincte.
* doit vérifier si la phrase exprimée par le joueur non JV est correcte et si sa proposition est valide en répondant de __manière très polie__. Exemple: "désolé XXX, mais vous n'avez qu'un roi"
* doit afficher le nombre de cartes de chaque JV, mais pas ses valeurs de carte.
* doit afficher vos cartes (celles du joueur non JV), de manière ordonnées du plus fort au plus faible suivant l'ordre décrit ci-dessous.
* doit pour toutes les actions effectuées par l'application afficher un message clair.
* Par exemple, s'il y a un mélange des cartes, un messages du type _"je viens de …."_ sera affiché.
* choix du nombre de points déclenchant la fin du jeu

=== Contraintes à respecter
* Dans ce jeu, un joueur peu décider d'abandonner s'il juge qu'il n'a aucune chance de gagner.
  C'est un événement rare (surtout chez les JV), mais possible.
* On mémorisera l'historique d'une partie dans une collection stockée dans un fichier.
  - il sera donc possible de rejouer une partie ou d'afficher le déroulé d'une partie
* Une interface spécifique pourra être proposée pour une aide ou pour voir le nombre de parties gagnées par chaque joueur.
* Vous devez implementer un Moteur de Jeu **MJ** qui joue comme un enfant.
  - L'enfant se débarrasse de ses cartes au fur et à mesure sans aucun assemblage de ses cartes.
    Par exemple, il ne va pas decider de faire une suite de 6 cartes, sachant que cela nécessite de briser des couples ou trio de cartes de même valeur.
* Vous devez également implémenter au moins un MJ qui joue de manière plus sophistiquée.
  - Par exemple, je peux jouer 1, 2 ou 3 cartes identiques, mais si j'ai 3 cartes identiques, je peux aussi decider de les jouer une par une, ou bien d'en jouer une suivie de deux.
  - Il existe de nombreuses autres stratégies.
    Ces stratégies dépendent des cartes en main.
    La problématique est de décider comment assembler vos cartes pour optimiser vos chances de pouvoir vous en débarrasser le plus rapidement possible.
  - Notez que plus les cartes sont faibles, plus il est difficile de s'en débarrasser.
  - Au delà de deux MJ et s'ils sont _vraiment différents_ et que vous l'expliquez dans le rapport, vous aurez des points bonus
* Une interface spécifique pourra être proposée pour "espionner" un joueur.
  En d'autres termes, il est possible d'afficher les sorties d'un MJ et voir ses cartes pour comprendre sa décision.
  Cela peut être le log d'un MJ qui affiche chacune de ses décisions.
* Si vous avez `m` MJ et `v` JV, le JV[i] i in (0..v-1) est piloté par le MJ[i modulo m].
  Chaque joueur virtuel est donc associé à un `MJ` différent.

== Extensions optionnelles
* Variantes (https://boardgamegeek.com/boardgame/215/tichu)
* plus de 2 MJ

== Références

**Attention**: il existe plusieurs variantes, mais celui de reference est dans le premier lien avec les contraintes ci-dessus.

* Description du jeu:
  - https://boardgamegeek.com/boardgame/70451/zheng-fen
  - https://chrisenvadrouille.wordpress.com/2013/07/05/jour-46-les-regles-dun-jeu-de-cartes-chinois/
  - https://www.pagat.com/climbing/doudizhu.html


* https://github.com/lyudaio/jcards

* Quelques bibliothèques :
http://fusesource.github.io/jansi/[JAnsi] (couleur dans un terminal),
https://github.com/jline/jline3[JLine] (gestion des saisies)

=== Manuel utilisateur

> À compléter de manière exhaustive:
> Comment est gérer les différents utilisateurs ?
> Décrire la technique utiliser pour décider comment les joueurs virtuels décide l'assemblage des cartes. ?
> Y a t il possibilité qu'un joueur change d'assemblage des cartes en cours de parties et dans tout les cas décrire le pourquoi et le comment ? 
> Quelles sont les modifications/extensions à apporter si l'on veut qu'il n'y ai que des joueurs virtuels ?
> Quelles améliorations peut on envisager pour rendre le jeu plus intéressant/performant pour l'utilisateur ?
> Quelles évolutions peut-on envisager ?

=== Manuel technique
==== Compiler le projet
.Sous Linux
----
$ JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64/ ./mvnw package
----

.Sous Windows
----
> mvnw.cmd package
----

=== Exécuter l'application
----
$ java -jar target/zhangyao-1.0.jar
----

> À compléter :
> Comment consulter le rapport de couverture de code par les tests ?
> Quelles bibliothèques ont été utilisées et pourquoi ?
> Quel est le rôle des différentes classes ?
> Quels traitements sont réalisés pour gérer une commande saisie par l'utilisateur ? Donnez un exemple.
> Quelles améliorations peut-on envisager ?
